### ISSUE TITLE
Не хочет переименовывать файл

### ISSUE THREAD

**Issue by limavrik1** [kaimi-ru/yandex-music-download#10]
Привет!
Похоже срабатывает какое-то ограничение.
Например для трэка https://music.yandex.ru/album/1719036/track/15773883
Это пример из программы без дополнительного логирования:
[DEBUG] main::rename_track(922): CreateFileW failed with: Ñèñòåìå íå óäàåòñÿ íàéòè óêàçàííûé ïóòü
[DEBUG] main::rename_track(922): CreateFileW failed with: Ñèñòåìå íå óäàåòñÿ íàéòè óêàçàííûé ïóòü
[DEBUG] main::rename_track(922): CreateFileW failed with: Ñèñòåìå íå óäàåòñÿ íàéòè óêàçàííûé ïóòü
...
И далее бесконечный цикл с такой ошибкой.

Тут добавил три строчки логирования получил такое:
https://cloud.mail.ru/public/7QDp/ncwV3W611

**Comment by kaimi-** [comment]
Какая ОС и системная локаль?

**Comment by limavrik1** [comment]
Windows 10 (Build 16299).
Локаль RU.

**Comment by kaimi-** [comment]
Тогда еще вопрос, запуск через ActivePerl/Strawberry Perl/... или через windows linux subsystem?

**Comment by limavrik1** [comment]
ActivePerl version 5.26.1.2601
