### ISSUE TITLE
Русские имена плейлистов

### ISSUE THREAD

**Issue by ingtarius** [kaimi-ru/yandex-music-download#11]
Кажется он не может распарсить русские имена.
На 2 плейлистах, которые имеют названия на русском получаю ошибку:

> [INFO] Checking Yandex.Music availability                           
[OK] Yandex.Music is available                                      
[INFO] Fetching playlist info: 1000 [username]                     
[ERROR] Can't get track list info    

А скопированные треки в плейлист с английским названием - качает корректно

**Comment by ingtarius** [comment]
Ой, кажется там есть плейлисты особые, которые не как обычные.
Возможно ли выкачивать треки из плейлиста "Мне понравилось"?

**Comment by kaimi-** [comment]
Если он доступен публично, то возможно по прямой ссылке, как и в случае с другими листами.
Есть пример листа, который не скачивается?

**Comment by ingtarius** [comment]
https://music.yandex.ru/users/durashkov.leonid/playlists/3

Для примера

**Comment by kaimi-** [comment]
Попробуй обновись

**Comment by ingtarius** [comment]
Работает, огонь!
Спасибо большое!
