### ISSUE TITLE
Не удается скачать музыку в 320kbps

### ISSUE THREAD

**Issue by sashkent3** [kaimi-ru/yandex-music-download#12]
Доброго времени суток!
Не удается скачать ни один трек по следующей команде:
`perl ya.pl -u https://music.yandex.ru/album/2747498/track/23559960 --auth {39_digit_auth_header_token} --bitrate 320 --debug -d /music`
Получаю ошибку:
`[DEBUG] main::get_track_url(556): Can't find track with proper format & bitrate`
Делаю что-то не так, или просто лавочку прикрыли, и в HQ скачать уже ничего нельзя?
Спасибо за скрипт!

**Comment by kaimi-** [comment]
Нет под рукой токена. Если не сложно - на 525 строке вставить код:
`log_response($json_data);`
После этого запустить с теми же параметрами и скрипт должен создать файл с телом ответа в текущей директории. Вот его бы посмотреть

**Comment by sashkent3** [comment]
Файл он создает, но пустой. А еще в консоль дает выхлоп:
`Can't locate object method "as_string" via package {стена текста} at ya.pl line 1107.`

**Comment by kaimi-** [comment]
А, извиняюсь, `log_response($request);`, не посмотрел функцию логирования

**Comment by sashkent3** [comment]
Log:
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Sun, 30 Sep 2018 07:16:36 GMT
Content-Type: application/json;charset=utf-8
Client-Date: Sun, 30 Sep 2018 07:16:37 GMT
Client-Peer: 87.250.250.246:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=RU/O=Yandex LLC/OU=Yandex Certification Authority/CN=Yandex CA
Client-SSL-Cert-Subject: /C=RU/O=Yandex LLC/OU=ITO/L=Moscow/ST=Russian Federation/CN=partners.api.music.yandex.net
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
Client-Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

{"invocationInfo":{"hostname":"myt1-0127-86a-msk-myt-music-st-e72-18274.gencfg-c.yandex.net","req-id":"c79a1c64ec736f1f3cf5117bc1c5dc6d","exec-duration-millis":"1"},"result":[{"codec":"aac","bitrateInKbps":64,"gain":true,"preview":false,"downloadInfoUrl":"https://storage.mds.yandex.net/file-download-info/30632_9cffb87a.52657388.9.23559960/g64he?sign=32c654fd36addbe0a94aa3c93408fd846e741c23808307f1c2975b635e5fdea2&ts=5bb07890"},{"codec":"aac","bitrateInKbps":128,"gain":true,"preview":false,"downloadInfoUrl":"https://storage.mds.yandex.net/file-download-info/30632_9cffb87a.52657388.5.23559960/g128?sign=d69aa70b8ff249ee46876610542f8fcecdc4321f61d00ff106d4dc4cee421a23&ts=5bb07890"},{"codec":"mp3","bitrateInKbps":192,"gain":false,"preview":false,"downloadInfoUrl":"https://storage.mds.yandex.net/file-download-info/30632_9cffb87a.52657388.1.23559960/2?sign=9b0a6a2d47fde8445a4a20bf4441b4b942c2ffd64e84c1c5237520f0d50ee6d0&ts=5bb07890"},{"codec":"aac","bitrateInKbps":192,"gain":false,"preview":false,"downloadInfoUrl":"https://storage.mds.yandex.net/file-download-info/30632_9cffb87a.52657388.7.23559960/192?sign=83460955ea0f6b040bab44706ad60c67c369d21169f53b80b1270fc32b29a72b&ts=5bb07890"}]}

**Comment by kaimi-** [comment]
Есть неочевидный нюанс - токен должен быть указан в формате OAuth *****.
По этой причине и недоступно нужное качество. В принципе сейчас сделаю добавление префикса.

**Comment by sashkent3** [comment]
Т.е. --auth OAuth {39_digit_auth_header_token} должно работать?

**Comment by kaimi-** [comment]
В кавычках --auth "OAuth ..."

**Comment by sashkent3** [comment]
Хм... Все еще та же ошибка. Лог по сути не изменился.

**Comment by kaimi-** [comment]
Активная подписка на яндекс.музыку должна присутствовать на данном токене

**Comment by sashkent3** [comment]
Так и есть!

**Comment by sashkent3** [comment]
О! Оказалось что в двух разных запросах телефон послал два разных токена. Ввел второй и все получилось. Огромное спасибо!

**Comment by 4t4nner** [comment]
Подскажите, как можно получить токен?
Я так понимаю нужно выполнить
`
echo '32_length_client_id:client_secret' | base64 --encode
`

client_id я могу получить из паспорта, выбрав Яндекс.Музыку  https://passport.yandex.ru/profile/access?uid=MY_ID

Но откуда получить client_secret?

Что вводить после --mobile? Попытался запустить  без параметра, получил
`Value "--debug" invalid for option mobile (number expected)`

**Comment by kaimi-** [comment]
Из мобильного клиента перехватывать запросы с помощью какого-либо mitm-прокси.
