### ISSUE TITLE
Не запускается скрипт

### ISSUE THREAD

**Issue by glemag** [kaimi-ru/yandex-music-download#13]
Скачал последнюю версию, при запуске получаю ошибку
`perl ya.pl 
Please, install this modules: Mozilla::CA, MP3::Tag, Getopt::Long::Descriptive, LWP::UserAgent, LWP::Protocol::https, HTTP::Cookies, HTML::Entities`

**Comment by kaimi-** [comment]
Так написано же, что необходимо установить эти модули, чтобы скрипт мог работать

**Comment by ink-ru** [comment]
У меня такая же проблема в Linux. Установил модули через metacpan, но сообщение не пропадает.

**Comment by 4t4nner** [comment]
> Так написано же, что необходимо установить эти модули, чтобы скрипт мог работать

Может стоит внести в md?

```bat
# Mozilla::CA
sudo apt-get install perl-modules
sudo cpan -i Mozilla::CA

# MP3::Tag
sudo apt-get install libmp3-tag-perl

# Getopt::Long::Descriptive
sudo apt-get install libgetopt-long-descriptive-perl
```

**Comment by kaimi-** [comment]
> У меня такая же проблема в Linux. Установил модули через metacpan, но сообщение не пропадает.

Если не пропадает, значит Perl не находит в ```@INC``` эти модули. Если metacpan в какие-то нестандартные места их устанавливает, то можно прописать их: https://perlmaven.com/how-to-change-inc-to-find-perl-modules-in-non-standard-locations

**Comment by khomaldi** [comment]
> MP3::Tag

FOR WINDOWS.

Установите ActivePerl. Внутри будет уже всё необходимое. У меня не хватало только MP3::Tag. Я скачал его отсюда: [офф. сайт](https://metacpan.org/pod/MP3::Tag)

Потом открой скачанную папку и найди там папку MP3::Tag и вот только её скопируй в perl/lib.

**Comment by azam10x** [comment]
> > Так написано же, что необходимо установить эти модули, чтобы скрипт мог работать
> 
> Может стоит внести в md?
> 
> ```batchfile
> # Mozilla::CA
> sudo apt-get install perl-modules
> sudo cpan -i Mozilla::CA
> 
> # MP3::Tag
> sudo apt-get install libmp3-tag-perl
> 
> # Getopt::Long::Descriptive
> sudo apt-get install libgetopt-long-descriptive-perl
> ```

Spasibo

**Comment by vladmix77** [comment]
Please, install this modules: Mozilla::CA, File::Util
Не устанавливается Linux Mint 20.3
