### ISSUE TITLE
Перестала работать последняя версия

### ISSUE THREAD

**Issue by neiks** [kaimi-ru/yandex-music-download#19]
Не работает последняя версия скрипта
NL => IS_WIN ? "\015\012" : "\012",
./ya.pl -u https://music.yandex.ru/album/6153640/track/45788378 --debug
[DEBUG] main::print_perl_info(1144): OS: linux; Path: /usr/bin/perl; Version: v5.18.2
[INFO] Checking Yandex.Music availability
[OK] Yandex.Music is available
[INFO] Fetching album info: 6153640
[INFO] Album title: Different World
[INFO] Tracks total: 15
[INFO] Filtering single track: 45788378 [6153640]
[INFO] Trying to fetch track: Alan Walker, K-391, Emelie Hollow - Lily
[DEBUG] main::get_track_url(574): Can't find track with proper format & bitrate
[ERROR] Can't get track url
[OK] Done!

Предыдущая версия работает, но иногда криво сохраняет некоторые треки, как посмотреть версию не знаю.

**Comment by kaimi-** [comment]
Удивительно, что какая-то старая версия работает.
Вижу, что без аутентификации теперь в веб-версии и в мобильной недоступны полные версии треков.
Также старый способ парсинга JSON для веб-версии неактуален.

**Comment by neiks** [comment]
Вот эта версия работает, только есть проблемы с id3v24 там, поэтому некоторые файлы сохраняются с сгенерированными именами
http://ftp.neiks.net.ru/Stuff/111/ya.pl

**Comment by kaimi-** [comment]
> http://ftp.neiks.net.ru/Stuff/111/ya.pl

Она на сервере исполняется, вместо скачивания.
Проще наверное на gist.github.com загрузить или тут прикрепить.

**Comment by neiks** [comment]
Пардон - ftp://ftp.neiks.net.ru/Stuff/111/ya.pl <ftp://ftp.neiks.net.ru/Stuff/111/ya.pl>
