### ISSUE TITLE
some tracks&playlists not download

### ISSUE THREAD

**Issue by DaRoni** [kaimi-ru/yandex-music-download#2]
прилагаю файлик
[new.txt](https://github.com/kaimi-ru/yandex-music-download/files/77143/new.txt)

другой плейлись с 8 треками скачался нормально. пометил плейлист с 147 треками личным --не качается, публичным --не качается. Удалил треки и оставил всего 99 подумал может ограничение какое то на количество треков--не качает
[new 2.txt](https://github.com/kaimi-ru/yandex-music-download/files/77162/new.2.txt)

**Comment by egoroof** [comment]
Попробуйте заменить в адресе домен `.kz` на `.ru`

**Comment by DaRoni** [comment]
Так тоже пробовал, никак не влияет.

**Comment by egoroof** [comment]
Попробуйте вызывать с аргументом `mobile=0`

**Comment by kaimi-** [comment]
У меня не повторяется. Пересними лог, пустив трафик через локальный прокси (Telerik Fiddler или Charles Proxy), только предварительно CA импортируй в хранилище Windows.

**Comment by DaRoni** [comment]
--mobile=0 --Option mobile does not take an argument
--mobile ошибка та же [ERROR] Can't get track list info

**Comment by kaimi-** [comment]
> --mobile=0 --Option mobile does not take an argument
> --mobile ошибка та же [ERROR] Can't get track list info

Не самую свежую версию используешь, я недавно исправлял это.

**Comment by DaRoni** [comment]
вчера только обновлял вроде. Сейчас заново скачал скриптик 

D:\111>perl ya.pl --debug -u https://music.yandex.ru/users/dario891/playlists/1000 -d d:\111\
[INFO] Fetching playlist info: 1000 [dario891]
[DEBUG] main::get_playlist_tracks_info(604): Request failed
[ERROR] Can't get track list info

**Comment by kaimi-** [comment]
Что скачал то? Ошибка как будто в файле скрипта что-то не то. И все еще нужен лог с прокси, а через  mobile=0 быстро блокировку словишь, точнее капчу.

**Comment by egoroof** [comment]
@kaimi- а я последнее время вообще капчу не видел.. наверно пользователи жаловались и её отрубили.

**Comment by DaRoni** [comment]
Fidler и сертификат поставил, а как пустить через локальный прокси ещё не понял.

**Comment by kaimi-** [comment]
--proxy 127.0.0.1:8080 или какой там порт...

**Comment by DaRoni** [comment]
не знаю те ли файлы
[saz.zip](https://github.com/kaimi-ru/yandex-music-download/files/77233/saz.zip)

**Comment by kaimi-** [comment]
Надо еще в настройка включить расшифровку HTTPS-трафика.
Tools->Fiddler Options->HTTPS->Decrypt HTTPS traffic.

И убедиться, что при работе, в логе слева, запросы видны в расшифрованном виде, а не просто CONNECT и все.

**Comment by barabadzhi** [comment]
Та же фигня на Ubuntu Phone(тот же плейлист на десктопе отлично качался).

```
[INFO] Fetching playlist info: 1000 [плейлист]
[DEBUG] main::get_playlist_tracks_info(604): Request failed
[ERROR] Can't get track list info
```

PS: На десктопе все работает отлично!
PPS: Getopt::Long::Descriptive cpan'ом не собрался на armhf(телефон), пришлось тащить из репозитория.

**Comment by kaimi-** [comment]
Нужно больше логов, могу предложить самостоятельно вставить в районе 604 строки код print $request->as_string; и приложить результат.

Или скачать последнюю версию, она должна создать файл с содержимым ответа при использовании опции --debug.

**Comment by barabadzhi** [comment]
@kaimi- full write access  file system, even tried as superuser.
Here is my screenshot & logs.

![screenshot20160126_224839668](https://cloud.githubusercontent.com/assets/8407846/12593196/e4c1a9f6-c480-11e5-9512-29a97b04d77f.png)

[log_1453837666.txt](https://github.com/kaimi-ru/yandex-music-download/files/105574/log_1453837666.txt)

**Comment by kaimi-** [comment]
А в логе написано:
LWP will support https URLs if the LWP::Protocol::https module
is installed.

**Comment by barabadzhi** [comment]
@kaimi- Уже прочел. Пофиксил.
Вот так:
1. Попытка установки `LWP::Protocol::https` через `cpan` дала ошибку.
2. Уcтановил из репозитория: `sudo apt install liblwp-protocol-https-perl -y`
3. Profit!
Итого:
  Ошибка вызывается отсутствием `LWP::Protocol::https`.
  Фиксится установкой оного.
  Непонятно правда, почему он не является обязательной зависимостью и скрипт без него запускается. Имхо, было бы лучше сделать зависимость жесткой (не знаток perl, но думаю такое можно сделать).
 PS: Лучше бы лог именовать с суффиксом ".txt" в конце, а то не поняло тип файла. Просто, для удобства.
 PPS: думаю баг можно закрывать. =З

**Comment by kaimi-** [comment]
В требования скрипта добавил, по идее будет ругаться, не модуль не установлен.
