### ISSUE TITLE
Downloads only 30 seconds

### ISSUE THREAD

**Issue by AndreyMZ** [kaimi-ru/yandex-music-download#20]
yandex-music-downloader only downloads a part of a track 30 seconds long. I have used `--cookie` option. However, in a web browser, while authenticated with the same cookie, I can listen a whole track.

**Comment by kaimi-** [comment]
Have you passed the whole cookie including name?
For example: --cookie "Session_id=abc....."

**Comment by AndreyMZ** [comment]
I have tried both with and without the cookie name.

Below is an example of a full command line I used (with the cookie name). (Of course, this cookie of my account is not active anymore.)
~~~
C:\Music>docker run --rm -v "%CD%":/root -it yandex-music-downloader --dir /root --cookie "Session_id=3:1597242679.5.0.1597242679377:5vJnVw:c.1|105957968.0.2|221325.195078.eQ5mjlHxIeOooqWDKm9_4khmIBw" --url https://music.yandex.ru/album/11496575/track/69007739
~~~

**Comment by kaimi-** [comment]
Mobile API was used by default, for which different authentication data is required.
Please, try latest version, issue seems to be resolved.

**Comment by AndreyMZ** [comment]
I have checked, it works OK now. Thank you!
