### ISSUE TITLE
скачивает только 618 Кбайт

### ISSUE THREAD

**Issue by lmike-mnc** [kaimi-ru/yandex-music-download#25]
Замечательный инструмент, спасибо
но есть проблема ("в шапке")
указываю --cookie='Session_id:....'
м.б. я чего-то не так указываю
куки брал из ФайрФокса
пробовал и sessionid2 и вместе с Session_id
заход из браузера по ссылке (если -l) дает тот же эффект - тоько 30сек

**Comment by kaimi-** [comment]
Если с флагом `--debug` запустить, то cookie корректно отображается, идентичен тому, что передан в качестве аргумента?

**Comment by lmike-mnc** [comment]
> 
> 
> Если с флагом `--debug` запустить, то cookie корректно отображается, идентичен тому, что передан в качестве аргумента?

за исключением кавычек

**Comment by kaimi-** [comment]
Только что обратил внимание. А почему после `Session_id` стоит двоеточие?
Должно быть что-то вроде `Session_id=3:16...`.
Т.е. `--cookie "Session_id=3:16...`.

**Comment by lmike-mnc** [comment]
согласен - тут я что-то про... упустил
Спасибо большое!
всё сработало :)
