### ISSUE TITLE
Very nice work! But it seems I get blocked by yandex after a few Downloads

### ISSUE THREAD

**Issue by xforze** [kaimi-ru/yandex-music-download#26]
Hi!
I have your Script running with my Yandex Plus Account and russian VPN.
I can download the first ~10 Songs without any Problems. But from this Time on, I get always the message:
```
[ERROR] Can't get track list info                                      
[INFO] Checking Yandex.Music availability                           
[OK] Yandex.Music is available                                      
[INFO] Fetching album info: 9454617  
```
Do you also experience this Problem ?

Do you know if it is possible to decrypt/convert downloaded Songs by the Yandex Android App ?
I can download and find the files on the Storage from the mobile Device but Im not able to play it.

Best Regards!

**Comment by kaimi-** [comment]
Hello,
Try to use `--delay 10` argument, default delay is 5, probably it will be possible to download more songs in a row.
I assume Yandex can detect downloader behavior based on rapid song downloads.

Regarding decryption there are some projects:
https://4pda.ru/forum/index.php?showtopic=898105
https://github.com/gavt45/yandexMusicDecoder

**Comment by xforze** [comment]
Hi!,

Thank you, I will try the delay Option. I already figured out that the IP-Block will be removed after a while.
I will let you know my finding.

Cheers!

**Comment by acherkashin** [comment]
@xforze 

you can download an audio by using VsCode extension

![image](https://user-images.githubusercontent.com/9947582/104855954-c4c4f600-5920-11eb-82b6-7f7c043d2a18.png)

[Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=acherkashin.yandex-music-extension)
[Repository](https://github.com/acherkashin/yandex-music-extension)

**Comment by naur5m** [comment]
@kaimi- Thank you for your app. It is gorgeous. Your suggestion to add --delay 10 is working perfect. I noticed that in average 10-15% of tracks from playlist can not be downloaded from playlist following error appears: "[ERROR] Can't get track url" 
Can you please advise whether it is possible to add some code so that ya.pl retry to download those tracks with error? Thank you in advance!

**Comment by kaimi-** [comment]
@naur5m Hello, try running it with `--debug` argument. It should save responses to the failed requests. Might be useful to figure out the reason.
