### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by neiks** [kaimi-ru/yandex-music-download#27]
[DEBUG] main::print_debug_info(1226): OS: linux; Path: /usr/bin/perl; Version: v5.18.2
[DEBUG] main::print_debug_info(1228): Cookie: 3:1606303467.5.0.********8580:zIvsLg:e.1|176462006.0.2|226361.948517.z5q5H1BeobpDlqzTANIzndzV6Es
[INFO] Checking Yandex.Music availability
[OK] Yandex.Music is available
[INFO] Fetching album info: 12903800
[DEBUG] main::get_album_tracks_info(666): Request failed
[DEBUG] main::log_response(1215): Response stored at log_1606303606
[ERROR] Can't get track list info

**Comment by kaimi-** [comment]
Hello,
I need a `log_1606303606` file contents to determine possible issue, current script version from the repository seems to be working fine

**Comment by neiks** [comment]
HTTP/1.1 404 Not found
Connection: Close
Client-Date: Wed, 25 Nov 2020 11:26:46 GMT
Client-Peer: 213.180.204.186:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=RU/O=Yandex LLC/OU=Yandex Certification Authority/CN=Yandex CA
Client-SSL-Cert-Subject: /C=RU/L=Moscow/OU=ITO/O=Yandex LLC/CN=*.music.yandex.ru
Client-SSL-Cipher: ECDHE-RSA-AES128-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
Client-Transfer-Encoding: chunked
NEL: {"report_to": "network-errors", "max_age": 86400, "success_fraction": 0.001, "failure_fraction": 0.1}
Report-To: {"group": "network-errors", "max_age": 86400, "endpoints": [ { "url": "https://dr.yandex.net/muz_nel"}]}
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

**Comment by kaimi-** [comment]
Sorry for the delay in response, can you confirm, that this issue is reproducible in the current version?
