### ISSUE TITLE
Why script downloads only 30 seconds of track?

### ISSUE THREAD

**Issue by zhombie** [kaimi-ru/yandex-music-download#28]
Maximum download size is 551 KB (30 seconds)

**Comment by zhombie** [comment]
Command: 

`./ya.pl --cookie Session_id=220889.13967.iys11GO780b3ZP1mn7uLgAD7qXs -u https://music.yandex.kz/album/13163680/track/75077074 --bitrate 320`

How to set cookie properly? Because Session_id consists of 3 parts, which is divided by | symbol. For ex, `3:1596458705.5.0.1584954297303:a-Nasg:50.1|506752503.-1.2.1:88373140|220889.13967.iys11GO780b3ZP1mn7uLgAD7qXs`

**Comment by AlexSnowLeo** [comment]
Confirm. 
I started uploading a track with authorization via --cookie.
For an example format: --cookie Session_id:"..."
https://music.yandex.ru/album/4684612/track/36517401
But only 30 seconds were uploaded - it looks like only an introductory version of the track.

**Comment by kaimi-** [comment]
@AlexSnowLeo please, provide an output with `--debug` flag, probably the Cookie value is passed incorrectly

**Comment by AlexSnowLeo** [comment]
@kaimi- I've try to run this command with --debug flag:
`perl ya.pl -u https://music.yandex.ru/album/4684612/track/36517401 --cookie Session_id:"3:1612458783.5.0.1604577691103:VWDeTQ:48.1|26663527.5645847.2.2:5645847|229789.721203.HlM3dVzIjkvlkN-U2e_Q8ZEIjyM" --debug`

I've got sessionId from here: 
![2021-02-04 224027](https://user-images.githubusercontent.com/1458178/106932842-084d9b80-673a-11eb-9aa5-b94bfd3381b4.png)


**Output:**

PS D:\Work\PL> perl ya.pl -u https://music.yandex.ru/album/4684612/track/36517401 --cookie Session_id:"3:1612458783.5.0.1604577691103:VWDeTQ:48.1|26663527.5645847.2.2:5645847|229789.721203.HlM3dVzIjkvlkN-U2e_Q8ZEIjyM" --debug

[DEBUG] main::print_debug_info(1225): Yandex Music Downloader v1.1


[DEBUG] main::print_debug_info(1226): OS: MSWin32; Path: D:\Work\Strawberry\perl\bin\perl.exe; Version: v5.32.1
[DEBUG] main::print_debug_info(1228): Cookie: Session_id:3:1612458783.5.0.1604577691103:VWDeTQ:48.1|26663527.5645847.2.2:5645847|229789.721203.HlM3dVzIjkvlkN-U2e_Q8ZEIjyM
[INFO] Checking Yandex.Music availability
[OK] Yandex.Music is available
[INFO] Fetching album info: 4684612
[INFO] Album title: Hvel
[INFO] Tracks total: 12
[INFO] Filtering single track: 36517401 [4684612]
[INFO] Trying to fetch track: Árstíðir - Ró
[DEBUG] main::get_track_url(648): Track url: https://s247man.storage.yandex.net/get-mp3/2ae2161dfd6764dd61caada07bd5f95b/0005ba86aefdc30c/rmusic/U2FsdGVkX19INc6ReFFEur0z4WJvyhU0QJze5PgV0KltrEa19iV5E4QGgNErqZt-z168yMdvcraDRd5cSrWYodq7AJxYrUKQK4yzt4N0Yck/93edfba332cc19d7228279aee3f2f8d8e25b8332572f5c28f6e59250f82362bc/5335?track-id=36517401&from=service-10-track&similarities-experiment=default
[DEBUG] main::download_track(522): File size from header: 485988
[DEBUG] main::download_track(546): Actual file size differs from expected (480653/485988)
[OK] Temporary saved track at sBODoEO2lz
[DEBUG] main::fetch_album_cover(989): Cover url: https://avatars.yandex.net/get-music-content/97284/c5ce86f1.a.4684612-1/400x400
[DEBUG] main::write_mp3_tags(958): add_frame: APIC=ARRAY(0x4e977f0)
[DEBUG] main::write_mp3_tags(958): add_frame: TPE1=Árstíðir
[DEBUG] main::write_mp3_tags(958): add_frame: TIT2=Ró
[DEBUG] main::write_mp3_tags(958): add_frame: TCON=folkrock
[DEBUG] main::write_mp3_tags(958): add_frame: TRCK=7
[DEBUG] main::write_mp3_tags(958): add_frame: TALB=Hvel
[DEBUG] main::write_mp3_tags(958): add_frame: TYER=2017
[DEBUG] main::write_mp3_tags(958): add_frame: TPE2=Árstíðir
[INFO] MP3 tags added for sBODoEO2lz
[INFO] sBODoEO2lz -> Árstíðir - Ró.mp3
[OK] Done!

**Comment by AlexSnowLeo** [comment]
Maybe this will help you figure it out. The "Yandex.Music" app for WIN10 downloads this file in the m3u8 streaming format and stores it encrypted. The m3u8 file with ts streaming files that I found locally will be attached to this message.
[67462665.zip](https://github.com/kaimi-io/yandex-music-download/files/5927485/67462665.zip)

**Comment by kaimi-** [comment]
Wrong cookie format. Should be as in the actual HTTP request. E.g.:
 `--cookie "Session_id=3:16124587..."`
