### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by ExoticMasterpiece** [kaimi-ru/yandex-music-download#30]
Hi there, may I know how to add it to path?

**Comment by kaimi-** [comment]
Hello,
Are you asking about adding a script itself to the system `PATH` variable, so you can call it from anywhere or about `--path` argument?

**Comment by ExoticMasterpiece** [comment]
Hi, thanks for the reply.  I am not sure what the address is to add in the path variable. Also, the system keeps repeating this instead of downloading the albums: 

Yandex Music Downloader v1.2

ya.pl [-adhklpstu] [long options...]
        -p[=INT] --playlist[=INT]  playlist id to download
        -k[=STR] --kind[=STR]      playlist kind (eg. ya-playlist,
                                   music-blog, music-partners, etc.)
        -a[=INT] --album[=INT]     album to download
        -t[=INT] --track[=INT]     track to download (album id must be
                                   specified)
        -u[=STR] --url[=STR]       download by URL
        -d[=STR] --dir[=STR]       download path (current direcotry will be
                                   used by default)
        --proxy STR                HTTP-proxy (format: 1.2.3.4:8888)
        --exclude STR              skip tracks specified in file
        --include STR              download only tracks specified in file
        --delay INT                delay between downloads (in seconds)
        --mobile INT               use mobile API
        --auth STR                 authorization header for mobile version
                                   (OAuth...)
        --cookie STR               authorization cookie for web version
                                   (Session_id=...)
        --bitrate INT              bitrate (eg. 64, 128, 192, 320)
        --pattern STR              track naming pattern
        --path STR                 path pattern

        Available placeholders: #number, #artist,
        #title, #album, #year

        Path pattern will be used in addition to
        the download path directory

        Example path pattern: #artist/#album-#year

        -l --link                  do not fetch, only print links to the
                                   tracks
        -s --silent                do not print informational messages
        --debug                    print debug info during work
        -h --help                  print usage

        --include and --exclude options use weak
        match i.e. ~/$term/      

        Example:                 
        ya.pl -p 123 -k ya-playlist
        ya.pl -a 123             
        ya.pl -a 123 -t 321      
        ya.pl -u https://music.yandex.ru/album/215690 --cookie ...
        ya.pl -u https://music.yandex.ru/album/215688/track/1710808 --auth ...
        ya.pl -u https://music.yandex.ru/users/ya.playlist/playlists/1257 --cookie ...

        © 2013-2021 by Kaimi (https://kaimi.io)

May I know a way to solve it?

**Comment by kaimi-** [comment]
For the `--path` variable syntax is following: `--path #artist/#album-#year`.
So there're some pre-defined placeholders which can be a part of path in any combination with static strings.
If you specify a `--path` parameter as in the example above, then tracks will be saved by the path like this:
`Queen/The Platinum Collection-2000/Queen - We Will Rock you.mp3`

Also, please provide a complete string, which you're using to start the script.
`--auth` or `--cookie` parameter values should be sanitized in your answer.

**Comment by ExoticMasterpiece** [comment]
Hmm, I still don't really understand it, but thanks anyway!
