### ISSUE TITLE
Use of uninitialized value $storage_path in substitution (s///) at ./ya.pl line 948.

### ISSUE THREAD

**Issue by T1MOXA** [kaimi-ru/yandex-music-download#31]
`Use of uninitialized value $storage_path in substitution (s///) at ./ya.pl line 948.`
Using current master build - https://github.com/kaimi-io/yandex-music-download/commit/38c1d68b42847af269060e5247f557db14d154ef

**Comment by T1MOXA** [comment]
And

```
Use of uninitialized value in string ne at ./ya.pl line 884.
Use of uninitialized value in string eq at ./ya.pl line 899.
```

**Comment by kaimi-** [comment]
Hello, can you please specify, what are you trying to download? Please, provide a URL or better a script launch arguments without a session.

**Comment by T1MOXA** [comment]
> Hello, can you please specify, what are you trying to download? Please, provide a URL or better a script launch arguments without a session.

./ya.pl --url https://music.yandex.ru/users/myUsername/playlists/3 --cookie "***" --exclude exclude.txt --dir ./download --debug

**Comment by kaimi-** [comment]
Please, try to update from the repository
