### ISSUE TITLE
main::get_playlist_tracks_info(758): Request failed

### ISSUE THREAD

**Issue by T1MOXA** [kaimi-ru/yandex-music-download#33]
```
HTTP/1.1 400 Bad request
<p>Если у вас возникли проблемы, пожалуйста, воспользуйтесь <a class="link" href="https://yandex.ru/support/smart-captcha/#help" 
```

ya.pl --url https://music.yandex.ru/users/user/playlists/3 --cookie "***" --exclude exclude.txt --dir ./download --debug

**Comment by pezhovski** [comment]
Had the same error. What worked for me was to copy Cookie entirely and not just Session_id
