### ISSUE TITLE
Пропускать существующие треки

### ISSUE THREAD

**Issue by Ravensof** [kaimi-ru/yandex-music-download#37]
привет. посмотрел примеры использования и поискал в issues, но похоже не прям такое есть.
можно ли сделать, чтобы скрипт сам не скачивал файл, если он уже есть?
я видел что можно указать файл со списком треков, которые не надо скачивать, но хотелось бы чтобы скрипт мог сам в список файлов заглядывать.
у меня очень много треков, не все за один проход скачиваются, и иногда новые появляются. хотелось бы автоматизировать это, не перекачивая все файлы.

**Comment by kaimi-** [comment]
Привет, добавил опцию

**Comment by Ravensof** [comment]
молниеносно, спасибо большое!

**Comment by naur5m** [comment]
> Привет, добавил опцию

How can I use skip existing track while downloading? Shall I add any argument?

**Comment by Ravensof** [comment]
@naur5m `--skip-existing`
it described in readme
