### ISSUE TITLE
Missing perl modules during install

### ISSUE THREAD

**Issue by britanik** [kaimi-ru/yandex-music-download#39]
Macos Monterey

Done all your instructions
Now running: 
`$ perl ya.pl -h`

Getting:
`Please, install this modules: Mozilla::CA, File::Util, MP3::Tag`

Running:
`cpanm Mozilla::CA, File::Util, MP3::Tag`

Getting:
```
! Finding Mozilla::CA, on cpanmetadb failed.
! Finding Mozilla::CA, () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Mozilla::CA,
! Finding File::Util, on cpanmetadb failed.
! Finding File::Util, () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution File::Util,
```

**Comment by kaimi-** [comment]
As far as I can see, those modules are present on `cpanmetadb`:

- https://cpanmetadb.plackperl.org/v1.0/package/Mozilla::CA
- https://cpanmetadb.plackperl.org/v1.0/package/File::Util
- https://cpanmetadb.plackperl.org/v1.0/package/MP3::Tag

You can try to provide a mirror URL or direct link to package as in `cpanm` [manual](https://metacpan.org/dist/App-cpanminus/view/bin/cpanm), e.g.:
`cpanm -v --mirror http://cpanmetadb.plackperl.org/ Mozilla::CA`
