### ISSUE TITLE
ID3 write_v24 error

### ISSUE THREAD

**Issue by cppmm** [kaimi-ru/yandex-music-download#40]
Got error with several files, that write_v24 disabled.
Fast fix:
`--- a/src/ya.pl
+++ b/src/ya.pl
@@ -128,6 +128,9 @@ for my $module(@{$req_modules{ALL}}, IS_WIN ? @{$req_modules{WIN}} : @{$req_modu
        }
 }
 
+# Configure modules
+MP3::Tag->config(write_v24 => 'TRUE');
+
 if(@missing_modules)
 {
        print 'Please, install this modules: ' . join ', ', @missing_modules;`

**Comment by kaimi-** [comment]
Hello, current script version (1.5) contains relevant code: https://github.com/kaimi-io/yandex-music-download/blob/master/src/ya.pl#L271

Are you using the latest version?

**Comment by cppmm** [comment]
Yes, latest. Now I see this code. Will check again later and will report if got error.
