### ISSUE TITLE
Bitrate always on 160kbps

### ISSUE THREAD

**Issue by cppmm** [kaimi-ru/yandex-music-download#41]
All files downloaded with bitrate 160. Option -bitrate 320 don't help.

**Comment by kaimi-** [comment]
Hello, please provide the arguments (without cookie/auth) with which you run the script

**Comment by cppmm** [comment]
Hi.
`./yandex-music-download/src/ya.pl --delay 2 -u https://music.yandex.ru/users/thecppmm/playlists/1001 --bitrate 320 --cookie Session_id='...'`

**Comment by kaimi-** [comment]
Can you confirm that you have an active subscription to Yandex music? High quality available only for subscribers.

**Comment by cppmm** [comment]
Yes. I have subscription.

**Comment by kaimi-** [comment]
This is odd, I can download at least first track of your playlist in 320k.
From what country are you trying to download?

**Comment by cppmm** [comment]
> From what country are you trying to download?

Russia.

Now its work. :/
Maybe it was temporary problem with yandex services?
Thanks for your help.
