### ISSUE TITLE
Yandex.Music is not availible

### ISSUE THREAD

**Issue by kristjanvariksoo** [kaimi-ru/yandex-music-download#5]
I cloned the repository and after installing the dependencies with cpan and figuring out I need to prepend commands with perl. I ran into the same error all the time and the script just wouldn't get me anything useful.

> kix@KiXBoX:~/yandex-music-download/src$ perl ya.pl -a=3155218Unknown option: =
> Unknown option: 3
> Unknown option: 1
> Unknown option: 5
> Unknown option: 5
> Unknown option: 2
> Unknown option: 1
> Unknown option: 8
> ya.pl [-adkptu] [long options...]
>   -p[=INT] --playlist[=INT]  playlist id to download
>   -k[=STR] --kind[=STR]      playlist kind (eg. ya-playlist,
>                              music-blog, music-partners, etc.)
>   -a[=INT] --album[=INT]     album to download
>   -t[=INT] --track[=INT]     track to download (album id must be
>                              specified)
>   -u[=STR] --url[=STR]       download by URL
>   -d[=STR] --dir[=STR]       download path (current direcotry will be
>                              used by default)
>   --proxy STR                HTTP-proxy (format: 1.2.3.4:8888)
>   --exclude STR              skip tracks specified in file
>   --include STR              download only tracks specified in file
>   --delay INT                delay between downloads (in seconds)
>   --mobile INT               use mobile API
> 
>   --debug                    print debug info during work
>   --help                     print usage
> 
>   --include and --exclude options use weak match i.e. ~/$term/
> 
>   Example:  
>   ya.pl -p 123 -k ya-playlist
>   ya.pl -a 123  
>   ya.pl -a 123 -t 321  
>   ya.pl -u https://music.yandex.ru/album/215690
>   ya.pl -u https://music.yandex.ru/album/215688/track/1710808
>   ya.pl -u https://music.yandex.ru/users/ya.playlist/playlists/1257
> kix@KiXBoX:~/yandex-music-download/src$ perl ya.pl -a 3155218
> [INFO] Checking Yandex.Music availability  
> [ERROR] Yandex.Music is not available  
> [INFO] Fetching album info: 3155218  
> [ERROR] Can't get track list info  
> kix@KiXBoX:~/yandex-music-download/src$ perl ya.pl -u https://music.yandex.ru/album/3155218
> [INFO] Checking Yandex.Music availability  
> [ERROR] Yandex.Music is not available  
> [INFO] Fetching album info: 3155218  
> [ERROR] Can't get track list info  
> kix@KiXBoX:~/yandex-music-download/src$ sudo perl ya.pl -u https://music.yandex.ru/album/3155218
> [INFO] Checking Yandex.Music availability  
> [ERROR] Yandex.Music is not available  
> [INFO] Fetching album info: 3155218  
> [ERROR] Can't get track list info  
> kix@KiXBoX:~/yandex-music-download/src$ ya.pl -u https://music.yandex.ru/album/215690
> ya.pl: command not found
> kix@KiXBoX:~/yandex-music-download/src$ perl ya.pl -u https://music.yandex.ru/album/215690
> [INFO] Checking Yandex.Music availability  
> [ERROR] Yandex.Music is not available  
> [INFO] Fetching album info: 215690  
> [ERROR] Can't get track list info  
> kix@KiXBoX:~/yandex-music-download/src$ perl ya.pl -u https://music.yandex.ru/album/215688/track/1710808
> [INFO] Checking Yandex.Music availability  
> [ERROR] Yandex.Music is not available  
> [INFO] Fetching album info: 215688  
> [INFO] Filtering single track: 1710808 [215688]  
> [ERROR] Can't get track list info  
> kix@KiXBoX:~/yandex-music-download/src$ ya.pl -u https://music.yandex.ru/users/ya.playlist/playlists/1257
> ya.pl: command not found
> kix@KiXBoX:~/yandex-music-download/src$ perl ya.pl -u https://music.yandex.ru/users/ya.playlist/playlists/1257
> [INFO] Checking Yandex.Music availability  
> [ERROR] Yandex.Music is not available  
> [INFO] Fetching playlist info: 1257 [ya.playlist]  
> [ERROR] Can't get track list info  
> kix@KiXBoX:~/yandex-music-download/src$

**Comment by kaimi-** [comment]
> [ERROR] Yandex.Music is not available

Yandex music service is not available in your country/for your current IP
