### ISSUE TITLE
[ERROR] Can't get track list info

### ISSUE THREAD

**Issue by korjavin** [kaimi-ru/yandex-music-download#7]
With any url:
[ERROR] Can't get track list info

**Comment by korjavin** [comment]
ya --debug -u https://music.yandex.ru/album/1754380/track/21287084                                                               
[INFO] Checking Yandex.Music availability                           
[OK] Yandex.Music is available                                      
[INFO] Fetching album info: 1754380                                 
[DEBUG] main::get_album_tracks_info(571): Request failed            
[DEBUG] main::log_response(1054): Response stored at log_1513165818 
[ERROR] Can't get track list info

**Comment by kaimi-** [comment]
Please, upload log_1513165818 file

**Comment by korjavin** [comment]
HTTP/1.1 451 Unavailable for Legal Reason
Connection: close
Date: Wed, 13 Dec 2017 12:16:50 GMT
Server: nginx
Content-Type: application/json;charset=utf-8
Client-Date: Wed, 13 Dec 2017 12:16:50 GMT
Client-Peer: 87.250.250.246:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=RU/O=Yandex LLC/OU=Yandex Certification Authority/CN=Yandex CA
Client-SSL-Cert-Subject: /C=RU/O=Yandex LLC/OU=ITO/L=Moscow/ST=Russian Federation/CN=partners.api.music.yandex.net
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
Client-Transfer-Encoding: chunked

{"invocationInfo":{"req-id":"00146d939a0f5593e39d92da6db09c21","hostname":"back02i.music.yandex.net"},"error":{"name":"Illegal region","message":"Illegal region"}}

**Comment by korjavin** [comment]
Yandex just doesn't like me, right?

**Comment by kaimi-** [comment]
Looks like availability check should be upgraded

**Comment by korjavin** [comment]
In the same time It's accesible from web page though

**Comment by kaimi-** [comment]
Made some changes, please try with current version

**Comment by korjavin** [comment]
Now:
```
[INFO] Checking Yandex.Music availability                           
[ERROR] Yandex.Music is not available
```
huh. Should I say better?

**Comment by kaimi-** [comment]
Yep, because "Illegal region". Seems your IP is not from permitted country

**Comment by korjavin** [comment]
ok ;) Thank you.
