### ISSUE TITLE
Can i get my "Liked" tracks or get text list of album/"Liked"/playList?

### ISSUE THREAD

**Issue by 4t4nner** [kaimi-ru/yandex-music-download#9]
Можно ли скачивать "Мне нравится"? А получать список песен по урлу?
Если нет, то вношу предложение для следующей версии)

(
Can i get my "Liked" tracks or get text list of album/"Liked"/playList by url?
)

**Comment by kaimi-** [comment]
Можно, если сделать список публичным. На него есть отдельная ссылка.
Скачивать по урлу можно.
